#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/crop-by-vincent:latest@sha256:ef87604cfcea745bcd8641f4295a0b171e5155072a39f96699c74f8992ddf8c5
    restart: on-failure:5
    environment:
      - PORT=3000
    ports:
      - "3013:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
