#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/crop-by-vincent:latest@sha256:0e84e5f425440668834bc207d5f4386430c5f27d5609071c947acccae45d952b
    restart: on-failure:5
    environment:
      - PORT=3000
    ports:
      - "3013:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
