#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/crop-by-vincent:latest@sha256:6db5616de326b03793becba9c65e43e4d4448e50f2e61a119feeeaead24d8eaf
    restart: on-failure:5
    environment:
      - PORT=3000
    ports:
      - "3013:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
